//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MaterialsEntities : DbContext
    {
        public MaterialsEntities()
            : base("name=MaterialsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<PartNumber> PartNumbers { get; set; }
    
        public virtual ObjectResult<GetGridViewData_Result> GetGridViewData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGridViewData_Result>("GetGridViewData");
        }
    }
}
