//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PartNumber
    {
        public int PKPartNumber { get; set; }
        [Required(ErrorMessage = "Part Number can't be empty")]
        public string PartNumber1 { get; set; }
        [Required(ErrorMessage = "Select a customer")]
        public int FKCustomer { get; set; }
        public bool Available { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
